In [1]:
from train import ResNet

resnet = ResNet()

pytorch_total_params = sum(p.numel() for p in resnet.parameters())
print(f"Total number of parameters in ResNet: {pytorch_total_params}")

Total number of parameters in ResNet: 46051484


In [ ]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
c = a,b
for i,j in zip(c):
    print(i,j)

ValueError: not enough values to unpack (expected 2, got 1)

In [ ]:
import torch
#torch.tensor([1,2,3,4,5]).to(torch.device("cuda:0"))
torch.ones(2)
torch.append

tensor([1., 1.])

In [14]:
from train import ResNet
import torch

resnet = ResNet()
resnet.to("cuda:0")
input_ = torch.randn( 8, 6, 6).to("cuda:0")
batch_input = torch.stack([i for i in input_]).to("cuda:0")
output = resnet(input_)
print(output.shape)

torch.Size([17])


In [ ]:
a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
a[-16],a[-1],[i for i in range(1, 17)]

(2, 17, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

In [20]:
a = torch.tensor([])
b = torch.tensor([1,2,3,4,5])
c = torch.cat((a, b), dim=0)
print(c)

tensor([1., 2., 3., 4., 5.])


In [23]:
import numpy as np
#np.shape(np.full((7,6,6),np.zeros((6,6))))
np.random.random()
torch.rand(1).item()

0.9052805304527283

In [25]:
alpha = torch.full((16,), 0.03)
eta = np.random.dirichlet(alpha, 1)[0]
print(eta)

[7.34653191e-22 3.27368419e-09 4.85577779e-09 1.66262952e-25
 4.67082453e-10 1.61774747e-29 1.59238611e-16 2.77080570e-08
 2.42055226e-04 1.51383059e-05 2.29721158e-15 9.99741935e-01
 3.03777494e-45 2.64655918e-50 3.69588647e-13 8.35528812e-07]


In [26]:
dirichlet_dist  = torch.distributions.Dirichlet(alpha)
eta = dirichlet_dist.sample()
print(eta)

tensor([3.6570e-03, 8.5624e-14, 1.6079e-33, 1.1755e-38, 9.6831e-01, 2.0166e-02,
        1.1755e-38, 8.8565e-06, 4.2632e-05, 4.4103e-06, 2.8642e-05, 1.3371e-05,
        1.0931e-17, 1.9887e-23, 7.7673e-03, 3.8773e-13])


In [54]:
np.random.choice(5, p=[0.1,0.2,0.3,0.2,0.2])
torch.distributions.multinomial(torch.tensor([0.1,0.2,0.3,0.2,0.2]), num_samples=1, replacement=True)

TypeError: 'module' object is not callable

In [59]:
a = torch.tensor([  0.,  26.,   0., 280.,   0.,  32.,  70.,  66.,  84.,  71.,   0.,   0., 0.,  77.,  48.,  47.])
probs = a / sum(a)
probs = [0.3,0.2]
print(np.random.choice(len(probs), p=probs))

ValueError: probabilities do not sum to 1

In [60]:
dict = {'a':1, 'b':2, 'c':3}
print(dict.a)

AttributeError: 'dict' object has no attribute 'a'

In [61]:
from train import score_count
with open("triple_web/game_records/game_20250725_182543.json", "r") as f:
    import json
    experience = json.load(f)
score = score_count(experience)
print(score)

4662


In [62]:
a = [0.03241895139217377,
            0.04862842708826065,
            0.04987531155347824,
            0.031172070652246475,
            0.12094762921333313,
            0.16084788739681244,
            0.0685785561800003,
            0.021197007969021797,
            0.043640896677970886,
            0.03865336626768112,
            0.06359102576971054,
            0.11970074474811554,
            0.06608478724956512,
            0.06109725683927536,
            0.04738154634833336,
            0.02618453837931156]
sum(a)

1.0000000037252903

In [ ]:
def run():
    a = torch.multinomial(torch.tensor([0.1,0.2,0.3,0.2,0.2]), num_samples=1, replacement=True)
    print(a)

import multiprocessing
po = multiprocessing.Pool(4)
for i in range(0, 4):
    po.apply_async(run)
po.close()
po.join()

In [3]:
import torch
100//13

7